# Generated by Django 2.2 on 2019-04-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnals', '0002_auto_20190409_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
