# Generated by Django 2.2 on 2019-04-09 14:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurnals', '0004_auto_20190409_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
